// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd6CVB0gzIh8GgGbARucxs-NGFHap8lzI',
    appId: '1:901192473751:web:fe21befedd192c6ac01dd2',
    messagingSenderId: '901192473751',
    projectId: 'lingua-ee198',
    authDomain: 'lingua-ee198.firebaseapp.com',
    storageBucket: 'lingua-ee198.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4FH-FyeHesGuswQAb-HoPwEN8vWHihQs',
    appId: '1:901192473751:android:b0bd1fb528cc637fc01dd2',
    messagingSenderId: '901192473751',
    projectId: 'lingua-ee198',
    storageBucket: 'lingua-ee198.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPB3d-ClYdXyFX123O4m0fbERqhVoFqZA',
    appId: '1:901192473751:ios:75397b26ab3b7580c01dd2',
    messagingSenderId: '901192473751',
    projectId: 'lingua-ee198',
    storageBucket: 'lingua-ee198.firebasestorage.app',
    iosBundleId: 'com.example.lingua',
  );
}
